services:
  app:
    ports:
      - "3000:3000"
    image: node:23.10.0
    restart: unless-stopped
    working_dir: /usr/src/app
    expose:
      - 3000
    tty: true
    volumes:
      - ./:/usr/src/app